### ISSUE TITLE
train_lstm_fusion crashes with CNMEM_STATUS_OUT_OF_MEMORY error

### ISSUE THREAD

**Issue by alvinwng** [anayebi/CS-224U-Project#1]
I was running this project on a MacBook Pro Retina with GeForce 750M, using the Theano backend. All the other training functions work except train_lstm_fusion, where it takes a much longer time before it starts displaying "Epoch 1/40", and would crash immediately with the following error:
> MemoryError: Error allocating 20160000 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).
Apply node that caused the error: GpuElemwise{mul,no_inplace}(GpuReshape{3}.0, GpuIncSubtensor{Set;::, int64::, ::}.0)
Toposort index: 5639
Inputs types: [CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D)]
Inputs shapes: [(300, 56, 300), (300, 56, 300)]
Inputs strides: [(16800, 300, 1), (16800, 300, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuCAReduce{add}{0,1,0}(GpuElemwise{mul,no_inplace}.0)]]

I'm not sure what's wrong with it. Could it be that the code wouldn't work on a GPU with 2GB memory? Any help would be greatly appreciated. Thanks.

**Comment by anayebi** [comment]
It's not an issue with the code, but just because the amount of GPU memory required appears to be exceeding the capacity of your GPU. Quick fixes would include using smaller batch sizes, or decreasing the sizes of the hidden states of the LSTMs (prior to the attentional layer).

**Comment by alvinwng** [comment]
I was able to get it running by reducing `max_sen_length` to 28. It seem the for loop in the `call` function of `TDistSoftAttention` is creating a large amount of codes that fills up the memory. I understand that the code is correct, but just wonder if there is a better way to reduce the memory requirement. The data itself doesn't seem to require that much memory.

**Comment by anayebi** [comment]
Yeah definitely, that's a great point. I had to do zeroing tricks with Theano in order to restrict the attention at every time point t to only go up to t and not past it. I'm sure though that could be optimized and improved (and might be more straight forward to do in TensorFlow, which Keras also supports).

**Comment by alvinwng** [comment]
I see. One last thing I noticed was that you were passing an `LSTM` to the constructor of `SoftAttentionConcat` instead of `LSTMMem`. Wouldn't that cause the attention to be applied to the outputs of the LSTM instead of its hidden states, as suggested in the PDF write-up? Nonetheless, thanks to your codes that I now have a better understanding of how Keras and its backend works. Nice work!

**Comment by alvinwng** [comment]
Please ignore my comment. I think I get it now. The h_t is the default output of the LSTM unit in Keras. Sorry for the misunderstanding.
